### ISSUE TITLE
도도 색기가 저 괴롭힘!

### ISSUE THREAD

**Issue by yellowoof24** [Dollar3795/HCS-School-Bruteforcer#1]
도도가 갑자기 이름 물어봐서 수상했는데
이거 때문이었음!!!!

**Comment by dodokorean** [comment]
아님. 저는 이거 있는지도 몰랐음

**Comment by Dollar3795** [comment]
피해를 입지 않은 것으로 보입니다, 피해를 입으셨다면 구체적인 피해 내용을 서술해 주세요

**Comment by CustomNPC** [comment]
저도 @Dollar3795 님의 말의 동이합니다

**Comment by CustomNPC** [comment]
@dodokorean 
![image](https://user-images.githubusercontent.com/67010072/157859013-506c0ab5-c8d1-4228-aade-b28ca75d5463.png)
해당 사진 해명 부탁드립니다

**Comment by ImNotTitanium** [comment]
와 생주

**Comment by CustomNPC** [comment]
> 아님. 저는 이거 있는지도 몰랐음
![image](https://user-images.githubusercontent.com/67010072/157859216-ddce0ba2-0874-43dc-a6c7-e8d534db73f4.png)
해명부탁^^

**Comment by dodokorean** [comment]
> @dodokorean [464×440 png54.3 kB![image](https://user-images.githubusercontent.com/67010072/157859013-506c0ab5-c8d1-4228-aade-b28ca75d5463.png)](https://user-images.githubusercontent.com/67010072/157859013-506c0ab5-c8d1-4228-aade-b28ca75d5463.png) 해당 사진 해명 부탁드립니다

해당 사진은, 조작된 사진으로 보입니다. 저는 링크를 유포한적이 없습니다.

**Comment by CustomNPC** [comment]
> 아님. 저는 이거 있는지도 몰랐음
@dodokorean 
![image](https://user-images.githubusercontent.com/67010072/157859216-ddce0ba2-0874-43dc-a6c7-e8d534db73f4.png)
해명부탁^^

**Comment by Dollar3795** [comment]
> > @dodokorean [464×440 png54.3 kB![image](https://user-images.githubusercontent.com/67010072/157859013-506c0ab5-c8d1-4228-aade-b28ca75d5463.png)](https://user-images.githubusercontent.com/67010072/157859013-506c0ab5-c8d1-4228-aade-b28ca75d5463.png) 해당 사진 해명 부탁드립니다
> 
> 해당 사진은, 조작된 사진으로 보입니다. 저는 링크를 유포한적이 없습니다.

![B80216F8-4212-4655-84BD-0DD074E778C1](https://user-images.githubusercontent.com/35988515/157859517-d3f5c51d-343f-44fe-bde0-fb55f896e96e.png)

확인 완료되었습니다 감사합니다.

**Comment by NotTitanium** [comment]
안넝하새요.. 도도님의 악성 doxxing으로 이ㄴ하요ㅛㅕ 피해를 입은 팃타ㄴㅠㅁ임미ㄷ ㅏ..

도도님이 이 프로그램을 이용해여 악의적인 목젓으로 제가 재학중인 학교를 doxxing하여서 유출하였슴미다...

저는 이것으로 인하여 정신적 충격을 입어서 틱장애가 생겼슴미다.. (아잇! 어! 푸르르!)

**Comment by Dollar3795** [comment]
> 안넝하새요.. 도도님의 악성 doxxing으로 이ㄴ하요ㅛㅕ 피해를 입은 팃타ㄴㅠㅁ임미ㄷ ㅏ..
> 
> 도도님이 이 프로그램을 이용해여 악의적인 목젓으로 제가 재학중인 학교를 doxxing하여서 유출하였슴미다...
> 
> 저는 이것으로 인하여 정신적 충격을 입어서 틱장애가 생겼슴미다.. (아잇! 어! 푸르르!)

구체적인 피해 내용과 함께 새로운 이슈를 열어주세요.

**Comment by ImNotTitanium** [comment]
응애 나생주

**Comment by jokk6703** [comment]
0도1도0님8이 제9 학1교6를5 뿌렸4습니다8.
너무 슬프0네요.

**Comment by ImNotTitanium** [comment]
하 진짜 나쁘신분이내오 ㅡㅡ
도도(염도경, 071130)님 그러케봣는대 실망입니다
